site_name: Blog Unix-administrator
site_description: Blog Unix-administrator

nav:
  - Home: index.md
  - User Guide:
    - Установка kuberenetes в ОС Talos: kubernetes-install-in-talos.md
    - Установка kuberenetes в ОС Ubuntu: kubernetes-install-in-ubuntu.md
    - Установка Harbor: harbor-install.md
    - Установка Gitlab-ce: gitlab-ce-install.md
    - Установка ArgoCD в Kubernetes: argocd-install-in-kubernetes.md
    - Основные команды Kubernetes: kubernetes-command.md
    - Основные команды talos: talos-command.md
  - Обо мне:
    - Контакты: contact.md
    - License: license.md
  - Музыка: musik.md

copyright: 'Copyright &copy; 2026 Anton Kardash'

theme:
  name:  mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  locale: ru
  highlightjs: true
  font:
    code: Roboto Mono
  hljs_languages:
    - yaml
    - rust
    - bash
    - shell
  markdown_extensions:
    - pymdownx.highlight:
        pygments_style: solarized-light # or solarized-dark
  extra:
    generator: false
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repositories/xiozip
    - icon: fontawesome/brands/github
      link: https://github.com/xiozip      